version: "3.0"

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # override sensitive values in docker-compose.override.yaml
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak_net

  keycloak:
    image: keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      # override sensitive values in docker-compose.override.yaml
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "4116:8080"
    depends_on:
      - postgres
    command:
      - start-dev
      - --hostname=localhost
      - --hostname-port=4116
    networks:
      - keycloak_net

networks:
  keycloak_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
